#!/usr/bin/env bash

set -e

PREFIX=
DOWNLOAD_CACHE=work
OPENRESTY_VER=
OPENSSL_VER=
LUAROCKS_VER=
BUILD_CACHE=1
ARTIFACT_CACHE=1
DEBUG=0
NPROC=`nproc`

PARAMS=""

main() {
  while (( "$#" )); do
    case "$1" in
      -p|--prefix)
        PREFIX=$2
        shift 2
        ;;
      -j|--jobs)
        NPROC=$2
        shift 2
        ;;
      --openresty)
        OPENRESTY_VER=$2
        shift 2
        ;;
      --openssl)
        OPENSSL_VER=$2
        shift 2
        ;;
      --luarocks)
        LUAROCKS_VER=$2
        shift 2
        ;;
      --no-build-cache)
        BUILD_CACHE=0
        shift 1
        ;;
      --no-artifact-cache)
        ARTIFACT_CACHE=0
        shift 1
        ;;
      --debug)
        DEBUG=1
        shift 1
        ;;
      --work)
        DOWNLOAD_CACHE=$2
        shift 2
        ;;
      -h|--help)
        show_usage
        exit 0
        ;;
      --) # end argument parsing
        shift
        break
        ;;
      -*|--*=) # unsupported flags
        echo "Error: Unsupported flag $1" >&2
        exit 1
        ;;
      *) # preserve positional arguments
        PARAMS="$PARAMS $1"
        shift
        ;;
    esac
  done
  # set positional arguments in their proper place
  eval set -- "$PARAMS"

  if [ -z "$PREFIX" ]; then
    show_usage
    fatal "prefix can not be empty"
  fi

  PREFIX=`pwd`/$PREFIX

  if [ -z "$OPENRESTY_VER" ]; then
    show_usage
    fatal "OpenResty version can not be empty"
  fi

  if [ -z "$OPENSSL_VER" ]; then
    show_usage
    fatal "OpenSSL version can not be empty"
  fi

  if [ $BUILD_CACHE == 0 ]; then
      rm -rf $DOWNLOAD_CACHE
  fi

  if [ $ARTIFACT_CACHE == 0 ]; then
      rm -rf $PREFIX
  fi

  OPENSSL_DOWNLOAD=$DOWNLOAD_CACHE/openssl-$OPENSSL_VER
  OPENRESTY_DOWNLOAD=$DOWNLOAD_CACHE/openresty-$OPENRESTY_VER
  OPENRESTY_PATCHES_DOWNLOAD=$DOWNLOAD_CACHE/openresty-patches-master

  mkdir -p $DOWNLOAD_CACHE $PREFIX

  notice "Building the components now..."

  OPENSSL_INSTALL=$PREFIX/openssl
  OPENRESTY_INSTALL=$PREFIX/openresty

  if [ ! -d $OPENSSL_INSTALL ]; then
    if [ ! -d $OPENSSL_DOWNLOAD ]; then
      warn "OpenSSL source not found, downloading..."
      pushd $DOWNLOAD_CACHE
        curl -s -S -L http://www.openssl.org/source/openssl-$OPENSSL_VER.tar.gz | tar xz
      popd
    fi

    notice "Building OpenSSL..."

    pushd $OPENSSL_DOWNLOAD
      if [ ! -f Makefile ]; then
          OPENSSL_OPTS=(
            "shared"
            "no-tests"
            "--prefix=$OPENSSL_INSTALL"
          )

          if [ $DEBUG == 1 ]; then
            OPENSSL_OPTS+=('-d')
          fi

        eval ./config ${OPENSSL_OPTS[*]}
      fi

      make
      make install_sw
    popd

    succ "OpenSSL $OPENSSL_VER has been built successfully!"

  else
    succ "OpenSSL $OPENSSL_VER has been built successfully (cached)!"
  fi

  if [ ! -d $OPENRESTY_INSTALL ]; then
    if [ ! -d $OPENRESTY_DOWNLOAD ]; then
      warn "OpenResty source not found, downloading..."
      pushd $DOWNLOAD_CACHE
        curl -s -S -L https://openresty.org/download/openresty-$OPENRESTY_VER.tar.gz | tar xz
      popd
    fi

    if [ ! -d $OPENRESTY_PATCHES_DOWNLOAD ]; then
      warn "Kong OpenResty patches not found, downloading..."
      pushd $DOWNLOAD_CACHE
        curl -s -S -L https://github.com/Kong/openresty-patches/archive/master.tar.gz | tar xz
      popd
    fi

    warn "Building OpenResty..."

    OPENRESTY_PATCHES_DOWNLOAD=`realpath $OPENRESTY_PATCHES_DOWNLOAD`

    pushd $OPENRESTY_DOWNLOAD
      if [ ! -f Makefile ]; then
        OPENRESTY_OPTS=(
          "--prefix=$OPENRESTY_INSTALL"
          "--with-cc-opt='-I$OPENSSL_INSTALL/include'"
          "--with-ld-opt='-L$OPENSSL_INSTALL/lib -Wl,-rpath,$OPENSSL_INSTALL/lib'"
          "--with-pcre-jit"
          "--with-http_ssl_module"
          "--with-http_realip_module"
          "--with-http_stub_status_module"
          "--with-http_v2_module"
          "--with-stream_ssl_preread_module"
          "--with-stream_realip_module"
          "-j$NPROC"
        )

        if [ $DEBUG == 1 ]; then
            OPENRESTY_OPTS+=('--with-debug')
            OPENRESTY_OPTS+=('--with-luajit-xcflags="-DLUAJIT_USE_VALGRIND -DLUA_USE_ASSERT -DLUA_USE_APICHECK -DLUAJIT_USE_SYSMALLOC"')
        fi

        pushd bundle
          if [ ! -f .patch_applied ]; then
            touch .patch_applied

            for patch_file in $(ls -1 $OPENRESTY_PATCHES_DOWNLOAD/patches/$OPENRESTY_VER/*.patch); do
              echo "Applying OpenResty patch $patch_file"
              patch -p1 < $patch_file
            done
          fi
        popd

        eval ./configure ${OPENRESTY_OPTS[*]}
      fi

      make -j$NPROC
      make install
    popd

    succ "OpenResty $OPENRESTY_VER has been built successfully!"

  else
    succ "OpenResty $OPENRESTY_VER has been built successfully (cached)!"
  fi


  if [ ! -z "$LUAROCKS_VER" ]; then
    LUAROCKS_INSTALL=$PREFIX/luarocks

    if [ ! -d $LUAROCKS_INSTALL ]; then
      LUAROCKS_DOWNLOAD=$DOWNLOAD_CACHE/luarocks-$LUAROCKS_VER

      if [ ! -d $LUAROCKS_DOWNLOAD ]; then
        warn "LuaRocks source not found, downloading..."
        pushd $DOWNLOAD_CACHE
          curl -s -S -L https://luarocks.org/releases/luarocks-$LUAROCKS_VER.tar.gz | tar xz
        popd
      fi

      warn "Building LuaRocks..."

      pushd $LUAROCKS_DOWNLOAD
        if [ ! -f config.unix ]; then
          ./configure \
            --prefix=$LUAROCKS_INSTALL \
            --lua-suffix=jit \
            --with-lua=$OPENRESTY_INSTALL/luajit \
            --with-lua-include=$OPENRESTY_INSTALL/luajit/include/luajit-2.1
        fi

        make build -j$NPROC
        make install
      popd

      succ "LuaRocks $LUAROCKS_VER has been built successfully!"

    else
      succ "LuaRocks $LUAROCKS_VER has been built successfully (cached)!"
    fi
  fi

  if [ $BUILD_CACHE == 0 ]; then
      rm -rf $DOWNLOAD_CACHE
  fi

  succ "Build finished in $SECONDS seconds. Enjoy!"
}

show_usage() {
  echo "Build basic components (OpenResty, OpenSSL and LuaRocks for Kong)"
  echo ""
  echo "Usage: $0 [options...] -p <prefix> --openresty <openresty_ver> --openssl <openssl_ver>"
  echo ""
  echo "Required arguments:"
  echo "  -p, --prefix                  location where components should be installed to"
  echo "      --openresty               version of OpenResty to build, such as 1.13.6.2"
  echo "      --openssl                 version of OpenSSL to build, such as 1.1.1b"
  echo "Optional arguments:"
  echo "      --no-build-cache          disable compilation caching and re-download source code to"
  echo "                                build from scratch"
  echo -e "                                \033[1;31mWARNING:\033[0m this removes everything inside the work directory"
  echo "      --no-artifact-cache       disable artifact caching and re-install all the softwares"
  echo -e "                                \033[1;31mWARNING:\033[0m this removes everything inside the prefix directory"
  echo "      --luarocks                version of LuaRocks to build, such as 3.0.4. if absent LuaRocks"
  echo "                                will not be built"
  echo "      --debug                   disable compile time optimizations and memory pooling for NGINX,"
  echo "                                LuaJIT and OpenSSL to help debugging"
  echo "      -j, --jobs                concurrency level to use when building, defaults to number of CPU"
  echo "                                cores available ($NPROC)"
  echo "      --work                    the working directory to use while compiling, defaults to \"work\""
  echo "  -h, --help                    show this usage"
}

notice() {
    builtin echo -en "\033[1m"
    echo "NOTICE: $@"
    builtin echo -en "\033[0m"
}

succ() {
    builtin echo -en "\033[1;32m"
    echo "SUCCESS: $@"
    builtin echo -en "\033[0m"
}

warn() {
    builtin echo -en "\033[1;33m"
    echo "WARN: $@"
    builtin echo -en "\033[0m"
}

fatal() {
    builtin echo -en "\033[1;31m"
    echo "FATAL: $@"
    builtin echo -en "\033[0m"
    exit 1
}

err() {
    builtin echo -en "\033[1;31m"
    echo "ERR: $@"
    builtin echo -en "\033[0m"
    exit 1
}


main $@
