#!/usr/bin/env bash

set -e

SCRIPT_PATH=$(dirname "$(realpath $0)")
PREFIX=
DOWNLOAD_CACHE=work
OPENRESTY_VER=
OPENSSL_VER=
LUAROCKS_VER=
PCRE_VER=
FORCE=0
OPENRESTY_PATCHES=master
DEBUG=0
NPROC=`nproc`
OS=
OS_VER=
NGINX_EXTRA_MODULES=()

PARAMS=""

main() {
  while (( "$#" )); do
    case "$1" in
      -p|--prefix)
        PREFIX=$2
        shift 2
        ;;
      -j|--jobs)
        NPROC=$2
        shift 2
        ;;
      --pcre)
        PCRE_VER=$2
        shift 2
        ;;
      --pcre_sha)
        PCRE_SHA=$2
        shift 2
        ;;
      --openresty)
        OPENRESTY_VER=$2
        shift 2
        ;;
      --openresty_sha)
        OPENRESTY_SHA=$2
        shift 2
        ;;
      --openssl)
        OPENSSL_VER=$2
        shift 2
        ;;
      --openssl_sha)
        OPENSSL_SHA=$2
        shift 2
        ;;
      --luarocks)
        LUAROCKS_VER=$2
        shift 2
        ;;
      --luarocks_sha)
        LUAROCKS_SHA=$2
        shift 2
        ;;
      --no-openresty-patches)
        OPENRESTY_PATCHES=0
        shift 1
        ;;
      --openresty-patches)
        OPENRESTY_PATCHES=$2
        shift 2
        ;;
      -f|--force)
        FORCE=1
        shift 1
        ;;
      --debug)
        DEBUG=1
        shift 1
        ;;
      --work)
        DOWNLOAD_CACHE=$2
        shift 2
        ;;
      --add-module)
        NGINX_EXTRA_MODULES+=("--add-module=$2")
        shift 2
        ;;
      -h|--help)
        show_usage
        exit 0
        ;;
      --) # end argument parsing
        shift
        break
        ;;
      -*|--*=) # unsupported flags
        echo "Error: Unsupported flag $1" >&2
        exit 1
        ;;
      *) # preserve positional arguments
        PARAMS="$PARAMS $1"
        shift
        ;;
    esac
  done
  # set positional arguments in their proper place
  eval set -- "$PARAMS"

  if [ -z "$PREFIX" ]; then
    show_usage
    fatal "prefix can not be empty"
  fi

  PREFIX=`realpath $PREFIX`
  DOWNLOAD_CACHE=`realpath $DOWNLOAD_CACHE`

  if [ -z "$OPENRESTY_VER" ]; then
    show_usage
    fatal "OpenResty version can not be empty"
  fi

  if [ -z "$OPENSSL_VER" ]; then
    show_usage
    fatal "OpenSSL version can not be empty"
  fi

  # retrieve OS info of OS-specific patches

  if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$NAME
    OS_VER=$VERSION_ID

  elif type lsb_release >/dev/null 2>&1; then
    OS=$(lsb_release -si)
    OS_VER=$(lsb_release -sr)
  fi

  if [ $FORCE == 1 ]; then
    rm -rf $PREFIX $DOWNLOAD_CACHE
  fi

  OPENSSL_DOWNLOAD=$DOWNLOAD_CACHE/openssl-$OPENSSL_VER
  OPENRESTY_DOWNLOAD=$DOWNLOAD_CACHE/openresty-$OPENRESTY_VER

  mkdir -p $DOWNLOAD_CACHE $PREFIX

  OPENSSL_INSTALL=${OPENSSL_INSTALL:-$PREFIX/openssl}
  OPENSSL_DESTDIR=${OPENSSL_DESTDIR:-/}
  OPENRESTY_RPATH=${OPENRESTY_RPATH:-$OPENSSL_INSTALL/lib}
  OPENRESTY_INSTALL=${OPENRESTY_INSTALL:-$PREFIX/openresty}
  OPENRESTY_DESTDIR=${OPENRESTY_DESTDIR:-/}

  notice "Downloading the components now..."

  pushd $DOWNLOAD_CACHE
    # OpenSSL

    if [[ ! -f $OPENSSL_DESTDIR$OPENSSL_INSTALL/bin/openssl && ! -d $OPENSSL_DOWNLOAD ]]; then
      warn "OpenSSL source not found, downloading..."
      curl -sSLO https://www.openssl.org/source/openssl-$OPENSSL_VER.tar.gz
      if [ ! -z ${OPENSSL_SHA+x} ]; then
        echo "$OPENSSL_SHA openssl-$OPENSSL_VER.tar.gz" | sha256sum -c -
      fi
      tar -xzvf openssl-$OPENSSL_VER.tar.gz
      ln -s openssl-$OPENSSL_VER openssl
    fi

    # OpenResty

    if [ ! -f $OPENRESTY_DESTDIR$OPENRESTY_INSTALL/nginx/sbin/nginx ]; then
      if [[ $OPENRESTY_PATCHES == 0 && -f $OPENRESTY_DOWNLOAD/bundle/.patch_applied ]]; then
        warn "Patched OpenResty found but vanilla requested, removing source..."
        rm -rf $OPENRESTY_DOWNLOAD

      elif [[ $OPENRESTY_PATCHES != 0 && ! -f $OPENRESTY_DOWNLOAD/bundle/.patch_applied ]]; then
        warn "Vanilla OpenResty found but patches requested, removing Makefile..."
        rm -f $OPENRESTY_DOWNLOAD/Makefile
      fi

      if [ ! -d $OPENRESTY_DOWNLOAD ]; then
        warn "OpenResty source not found, downloading..."
        curl -sSLO https://openresty.org/download/openresty-$OPENRESTY_VER.tar.gz
        if [ ! -z ${OPENRESTY_SHA+x} ]; then
          echo "$OPENRESTY_SHA openresty-$OPENRESTY_VER.tar.gz" | sha256sum -c -
        fi
        tar -xzvf openresty-$OPENRESTY_VER.tar.gz
      fi
    fi

    # PCRE

    if [ ! -z "$PCRE_VER" ]; then
      PCRE_DOWNLOAD=$DOWNLOAD_CACHE/pcre-$PCRE_VER
      if [ ! -d $PCRE_DOWNLOAD ]; then
        warn "PCRE source not found, downloading..."
        curl -sSLO https://ftp.pcre.org/pub/pcre/pcre-${PCRE_VER}.tar.gz
        if [ ! -z ${PCRE_SHA+x} ]; then
          echo "$PCRE_SHA pcre-${PCRE_VER}.tar.gz" | sha256sum -c -
        fi
        tar -xzvf pcre-${PCRE_VER}.tar.gz
        ln -s pcre-$OPENSSL_VER pcre
      fi
    fi

    # LuaRocks

    if [ ! -z "$LUAROCKS_VER" ]; then
      LUAROCKS_INSTALL=${LUAROCKS_INSTALL:-$PREFIX/luarocks}
      LUAROCKS_DESTDIR=${LUAROCKS_DESTDIR:-/}
      if [ ! -f $LUAROCKS_DESTDIR$LUAROCKS_INSTALL/bin/luarocks ]; then
        LUAROCKS_DOWNLOAD=$DOWNLOAD_CACHE/luarocks-$LUAROCKS_VER
        if [ ! -d $LUAROCKS_DOWNLOAD ]; then
          warn "LuaRocks source not found, downloading..."
          curl -sSLO https://luarocks.org/releases/luarocks-$LUAROCKS_VER.tar.gz
          if [ ! -z ${LUAROCKS_SHA+x} ]; then
            echo "$LUAROCKS_SHA luarocks-$LUAROCKS_VER.tar.gz" | sha256sum -c -
          fi
          tar -xzvf luarocks-$LUAROCKS_VER.tar.gz
        fi
      fi
    fi
  popd

  notice "Patching the components now..."

  if [ ! -f $OPENRESTY_DESTDIR$OPENRESTY_INSTALL/nginx/sbin/nginx ]; then
    notice "Patching OpenResty..."

    if [[ $OPENRESTY_PATCHES != 0 ]]; then
      pushd $DOWNLOAD_CACHE
        if [[ ! -d "openresty-patches" ]]; then
          warn "Kong OpenResty patches not found, cloning..."
          git clone https://github.com/Kong/openresty-patches
        fi

        pushd openresty-patches
          notice "Checking out branch '$OPENRESTY_PATCHES' of Kong's OpenResty patches..."
          git fetch
          git reset --hard origin/$OPENRESTY_PATCHES
        popd
      popd

      pushd $OPENRESTY_DOWNLOAD/bundle
        if [ ! -f .patch_applied ]; then
          for patch_file in $(ls -1 $DOWNLOAD_CACHE/openresty-patches/patches/$OPENRESTY_VER/*.patch); do
            notice "Applying OpenResty patch $patch_file"
            patch -p1 < $patch_file \
              || fatal "failed to apply patch: $patch_file"
          done

          touch .patch_applied
        fi
      popd

      if [ ! -f $OPENRESTY_DOWNLOAD/bundle/.patch_applied ]; then
        fatal "missing .patch_applied file; some OpenResty patches may not have been applied"
      fi
    fi

    # apply non Kong-specific patches

    if version_eq $OPENRESTY_VER 1.13.6; then
      if [[ $OS == "Fedora" && $OS_VER -gt 28 ]]; then
        warn "Fedora 28 or above detected, applying 'rm_glibc_crypt_r_workaround' patch..."
        pushd $OPENRESTY_DOWNLOAD/bundle/nginx-1.13.6
          patch --forward -p1 < $SCRIPT_PATH/patches/nginx-1.13.6-rm_glibc_crypt_r_workaround.patch || true
        popd
      fi
    fi
  fi

  notice "Building the components now..."

  # Building OpenSSL

  if [ ! -f $OPENSSL_DESTDIR$OPENSSL_INSTALL/bin/openssl ]; then
    notice "Building OpenSSL..."

    pushd $OPENSSL_DOWNLOAD
      if (version_lte $OPENSSL_VER 1.0 && [[ ! -d include/openssl ]]) || [[ ! -f Makefile ]]; then
          OPENSSL_OPTS=(
            "-g"
            "shared"
            "-DPURIFY"
            "no-threads"
            "--prefix=$OPENSSL_INSTALL"
            "--openssldir=$OPENSSL_INSTALL"
          )

          if version_gte $OPENSSL_VER 1.1.0; then
            OPENSSL_OPTS+=('no-unit-test')

          else
            OPENSSL_OPTS+=('no-tests')
          fi

          if [ $DEBUG == 1 ]; then
            OPENSSL_OPTS+=('-d')
          fi

        eval ./config ${OPENSSL_OPTS[*]} "-Wl,--enable-new-dtags,-rpath,'\$(LIBRPATH)'"
      fi

      make -j$NPROC
      make install_sw DESTDIR=${OPENSSL_DESTDIR}
    popd

    succ "OpenSSL $OPENSSL_VER has been built successfully!"

  else
    succ "OpenSSL $OPENSSL_VER has been built successfully (cached)!"
  fi

  # Building OpenResty

  if [ ! -f $OPENRESTY_DESTDIR$OPENRESTY_INSTALL/nginx/sbin/nginx ]; then
    notice "Building OpenResty..."

    pushd $OPENRESTY_DOWNLOAD
      if [ ! -f Makefile ]; then
        OPENRESTY_OPTS=(
          "--prefix=$OPENRESTY_INSTALL"
          "--with-cc-opt='-I$OPENSSL_DESTDIR$OPENSSL_INSTALL/include'"
          "--with-ld-opt='-L$OPENSSL_DESTDIR$OPENSSL_INSTALL/lib -Wl,-rpath,$OPENRESTY_RPATH'"
          "--with-pcre-jit"
          "--with-http_ssl_module"
          "--with-http_realip_module"
          "--with-http_stub_status_module"
          "--with-http_v2_module"
          "-j$NPROC"
        )

        if version_gte $OPENRESTY_VER 1.11.4; then
          OPENRESTY_OPTS+=('--with-stream_realip_module')
        fi

        if version_gte $OPENRESTY_VER 1.11.5; then
          OPENRESTY_OPTS+=('--with-stream_ssl_preread_module')
        fi

        if [ ! -z "$PCRE_VER" ]; then
          OPENRESTY_OPTS+=('--with-pcre=$PCRE_DOWNLOAD')
        fi

        OPENRESTY_OPTS+=(${NGINX_EXTRA_MODULES[@]})

        if [ $DEBUG == 1 ]; then
          OPENRESTY_OPTS+=('--with-debug')
          OPENRESTY_OPTS+=('--with-luajit-xcflags="-DLUAJIT_USE_VALGRIND -DLUA_USE_ASSERT -DLUA_USE_APICHECK -DLUAJIT_USE_SYSMALLOC"')
        fi

        eval ./configure ${OPENRESTY_OPTS[*]}
      fi

      make -j$NPROC
      make -j$NPROC install DESTDIR=${OPENRESTY_DESTDIR}
    popd

    succ "OpenResty $OPENRESTY_VER has been built successfully!"

  else
    succ "OpenResty $OPENRESTY_VER has been built successfully (cached)!"
  fi

  # Building LuaRocks

  if [ ! -z "$LUAROCKS_VER" ]; then
    if [ ! -f $LUAROCKS_DESTDIR$LUAROCKS_INSTALL/bin/luarocks ]; then
      notice "Building LuaRocks..."

      pushd $LUAROCKS_DOWNLOAD
        if [ ! -f config.unix ]; then
          ./configure \
            --prefix=$LUAROCKS_INSTALL \
            --lua-suffix=jit \
            --with-lua=$OPENRESTY_DESTDIR$OPENRESTY_INSTALL/luajit \
            --with-lua-include=$OPENRESTY_DESTDIR$OPENRESTY_INSTALL/luajit/include/luajit-2.1
        fi

        make build -j$NPROC
        make install DESTDIR=${LUAROCKS_DESTDIR}
      popd

      succ "LuaRocks $LUAROCKS_VER has been built successfully!"

    else
      succ "LuaRocks $LUAROCKS_VER has been built successfully (cached)!"
    fi
  fi

  succ "Build finished in $SECONDS seconds. Enjoy!"
}

parse_version() {
  [[ -z $1 ]] && fatal 'missing arg $1 when invoking parse_version()'
  [[ -z $2 ]] && fatal 'missing arg $2 when invoking parse_version()'

  # remove non-version parts of a version, ie foobar-1.2.3a.5-rc1 -> 1.2.3a.5
  local re='^[^0-9]*([0-9a-zA-Z.]*)$'
  local version=$(echo $1 | perl -0777 -pe "s/$re/\1/s")

  IFS='.' read -r -a $2 <<< "$version"
}

parse_nginx_core_version() {
  [[ -z $1 ]] && fatal 'missing arg $1 when invoking parse_nginx_core_version()'

  local nginx_ver

  parse_version $1 nginx_ver

  echo "${nginx_ver[0]}.${nginx_ver[1]}.${nginx_ver[2]}"
}

version_eq() {
  local version_a version_b

  parse_version $1 version_a
  parse_version $2 version_b

  # Note that we are indexing on the b components, ie: 1.11.100 == 1.11
  for index in "${!version_b[@]}"; do
    [[ "${version_a[index]}" != "${version_b[index]}" ]] && return 1
  done

  return 0
}

version_lt() {
  local version_a version_b

  parse_version $1 version_a
  parse_version $2 version_b

  local alpha_num_re='^([0-9]+)([a-zA-Z]*)$'
  local num_a num_b
  local alp_a alp_b

  for index in "${!version_a[@]}"; do
    num_a=$(echo ${version_a[index]} | perl -0777 -pe "s/$alpha_num_re/\1/s")
    num_b=$(echo ${version_b[index]} | perl -0777 -pe "s/$alpha_num_re/\1/s")
    [[ "$num_a" -lt "$num_b" ]] && return 0
    [[ "$num_a" -gt "$num_b" ]] && return 1

    alp_a=$(echo ${version_a[index]} | perl -0777 -pe "s/$alpha_num_re/\2/s")
    alp_b=$(echo ${version_b[index]} | perl -0777 -pe "s/$alpha_num_re/\2/s")
    [[ "$alp_a" < "$alp_b" ]] && return 0
    [[ "$alp_a" > "$alp_b" ]] && return 1
  done

  return 1
}

version_gt() {
  (version_eq $1 $2 || version_lt $1 $2) && return 1
  return 0
}

version_lte() {
  (version_lt $1 $2 || version_eq $1 $2) && return 0
  return 1
}

version_gte() {
  (version_gt $1 $2 || version_eq $1 $2) && return 0
  return 1
}

show_usage() {
  echo "Build basic components (OpenResty, OpenSSL and LuaRocks) for Kong."
  echo ""
  echo "Usage: $0 [options...] -p <prefix> --openresty <openresty_ver> --openssl <openssl_ver>"
  echo ""
  echo "Required arguments:"
  echo "  -p, --prefix <prefix>            Location where components should be installed."
  echo "      --openresty <openresty_ver>  Version of OpenResty to build, such as 1.13.6.2."
  echo "      --openssl <openssl_ver>      Version of OpenSSL to build, such as 1.1.1c."
  echo ""
  echo "Optional arguments:"
  echo "      --no-openresty-patches       Do not apply openresty-patches while compiling OpenResty."
  echo "                                   (Patching is enabled by default)"
  echo ""
  echo "      --openresty-patches <branch> Specify an openresty-patches branch to use when applying patches."
  echo "                                   (Defaults to \"master\")"
  echo ""
  echo "      --luarocks <luarocks_ver>    Version of LuaRocks to build, such as 3.1.2. If absent, LuaRocks"
  echo "                                   will not be built."
  echo ""
  echo "      --pcre <pcre_ver>            Version of PCRE to build, such as 8.43. If absent, PCRE will"
  echo "                                   not be build."
  echo ""
  echo "      --add-module <module_path>   Path to additional NGINX module to be built. This option can be"
  echo "                                   repeated and will be passed to NGINX's configure in the order"
  echo "                                   they were specified."
  echo ""
  echo "      --debug                      Disable compile-time optimizations and memory pooling for NGINX,"
  echo "                                   LuaJIT and OpenSSL to help debugging."
  echo ""
  echo "  -j, --jobs                       Concurrency level to use when building."
  echo "                                   (Defaults to number of CPU cores available: $NPROC)"
  echo ""
  echo "      --work <work>                The working directory to use while compiling."
  echo "                                   (Defaults to \"work\")"
  echo ""
  echo "  -f, --force                      Build from scratch."
  echo -e "                                   (\033[1;31mWARNING:\033[0m this removes everything inside the <work> and <prefix> directories)"
  echo ""
  echo "  -h, --help                       Show this message."
}

notice() {
  builtin echo -en "\033[1m"
  echo "NOTICE: $@"
  builtin echo -en "\033[0m"
}

succ() {
  builtin echo -en "\033[1;32m"
  echo "SUCCESS: $@"
  builtin echo -en "\033[0m"
}

warn() {
  builtin echo -en "\033[1;33m"
  echo "WARN: $@"
  builtin echo -en "\033[0m"
}

fatal() {
  builtin echo -en "\033[1;31m"
  echo "FATAL: $@"
  builtin echo -en "\033[0m"
  exit 1
}

err() {
  builtin echo -en "\033[1;31m"
  echo "ERR: $@"
  builtin echo -en "\033[0m"
  exit 1
}

if [[ $(basename $(realpath $0)) == "kong-ngx-build" ]]; then
  main $@
fi

# vi: ts=2 sts=2 sw=2 et
